name: Feature Request
description: Template for feature requests
title: '[Request]: '
labels: ["enhancement"]
assignees:
- asheroto
body:
- type: markdown
  attributes:
    value: |
      Thanks for taking the time to fill out this feature request!
- type: textarea
  id: feature
  attributes:
    label: Describe the feature or improvement you're requesting
    description: A clear and concise description of what you want to happen.
  validations:
    required: true
- type: textarea
  id: context
  attributes:
    label: Additional context
    description: Add any other context about the feature request here.
